<h2>Cadastro</h2>

<p>Querido leitor</p>
<p>A revista PHP Review é uma revista pública e gratuita, porém, para que você faça o download das edições é
necessário que realize o cadastro abaixo. Vale lembrar que você poderá baixar quantas vezes quiser as edições da
revista.</p>

<p><u><b>Atenção:</b> Todos os campos abaixo são obrigatórios</u></p>

<?php
  $this->form->setAction($this->url());
  echo $this->form;
?>