<h2>Cadastro</h2>

<p>Querido leitor</p>
<p>A revista PHP Review é uma revista pública e gratuita, porém, para que você faça o download das edições é
necessário que realize o cadastro abaixo. Vale lembrar que você poderá baixar quantas vezes quiser as edições da
revista.</p>

<p><b>Atenção:</b> Algumas propostas de patrocínio que nos foram entregues perguntavam algumas informações adicionais dos assinantes, por isso, apesar de extenso, todos os campos abaixo são obrigatórios<br />
Conto com a compreensão de todos.</p>

<?php
  $this->form->setAction($this->url());
  echo $this->form;
?>
