<h2>Welcome to <span>Corporate Template</span></h2>

      <p>This <a href="http://www.templatemo.com" target="_parent">free web template</a> is provided by <a href="http://www.templatemo.com" target="_parent">TemplateMo.com</a> website. You may use this template in your websites. Credit goes to <a href="http://www.photovaco.com" target="_blank">Free Photos</a> for photos. </p>
      <p>Fusce ac orci sit amet velit ultrices condimentum. Integer imperdiet odio ac eros. Ut id massa. Nullam nunc. Vivamus sagittis varius lorem.Maecenas aliquam, ligula id egestas suscipit, nisi sapien dignissim nibh, ac vestibulum lorem urna in neque.</p>
        <div class="readmore"><a href="#">read more</a></div>

        <div class="cleaner_h40"></div>
        
        <h2>Our <span>Services</span></h2>
        <p>	Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illovitae dicta sunt explicabo.</p>

        <div class="col_w265 float_l">
            <h3>Web Design</h3>
            <div class="two_col_image">
                <a href="#"><img src="images/templatemo_image_02.png" alt="image" width="249" height="105" /></a>            </div>
          <p>Aenean cursus aesf aecenas aliquam, ligula idegers estas suscipit, nisisapien dignissim nibh, acvestibulum lore mur nain neque. </p>
            <div class="readmore"><a href="#">read more</a></div>
        </div>

        <div class="col_w265 float_r">
            <h3>Photography</h3>
            <div class="two_col_image">
                <a href="#"><img src="images/templatemo_image_03.png" alt="image" width="249" height="105" /></a> </div>
          <p>Phasellus convallis facilisis risus vitae fringilla. Aliquam imperdiet, est at scelerisque tincidunt, orci ipsum mattis est.</p>
            <div class="readmore"><a href="#">read more</a></div>
        </div>