<h2>Nossa Equipe</h2>
<p>Formado por profissionais que atuam no mercado há mais de 5 anos, a PHP Review possui uma equipe especializada
naquilo que lhe compete, para que o resultado final seja agradavel a todos.</p>

<p>Inicialmente, a revista foi formada por apenas dois profissionais, mas com o passar do tempo alguns novos
amigos passaram a fazer parte da equipe técnica da revista, mas não chegariamos aqui se não houvesse apoio
dos principais grupos de usuários de PHP existentes no Brasil.</p>

<p>Atualmente, a equipe da revista e do portal é formada por:</p>
<ul>
    <li>Alexandre "Taz" (PHP SP)</li>
    <li>André Pinheiro (PHP Rio)</li>
    <li>Cibele Aviles (Designer)</li>
</ul>
<p>Nossa equipe ainda está crescendo!! Então, se estiver interessado em fazer parte da equipe, entre em contato
conosco.</p>

<div class="cleaner_h40"></div>

<h2>Faça Parte</h2>

<p>Como toda revista de qualidade, faz-se necessário uma equipe coesa e com profissionais específicos para
atuar em cada área da revista: Revisores, Redatores, Colunistas, reporteres, etc.</p>

<p>Por isso, estamos buscando profissionais realmente dedicados para fazer desta revista um grande marco
na história das publicações on-line</p>

<blockquote>Equipe PHP Review.</blockquote>