<h2>Sobre a Revista</h2>

<p>Depois de muita procura por conteúdos de fácil acesso na internet, não foi possível encontrar conteúdo
que abrangesse tanto a linguagem de programação quanto os assuntos que o envolvem.</p>

<p>Com esta perspectiva surgiu a PHP Review, que como todo projeto colaborativo, teve o seu nome escolhido
pela comunidade PHP. Desta forma a revista já nasceu com o compromisso de ser colaborativa, gratuita e
com qualidade. Apesar do começo ser colaborativo, tomamos o devido cuidado para que o projeto não fosse
demasiadamente grande no início para que o comprometimento, marca registrada dos programadores PHP, não
fosse perdido com o tempo, como ocorre em todo projeto que começa sem planejamento.</p>

<p>A PHP Review está e estará amadurecendo com o tempo, pois um upgrade das informações sempre acontece e de
vez em quando o seu próprio core acaba sendo atualizado para uma melhor utilização. Com esta filosofia
sabemos que a PHP Review não nasceu de um único projeto e nem continuará sendo sempre da mesma forma.</p>

<p>A partir de agora anuncio que a PHP Review finalmente está amadurecida o suficiente para a sua versão 1.0,
que trará além de conteúdo técnico para programadores PHP, muita informação para ser utilizada no seu dia
a dia do trabalho, proporcionando um maior conhecimento da linguagem, mercado de trabalho, novas tecnologias,
e muito mais. E convidamos você para fazer parte deste grupo que fará o upgrade da revista, enviando sempre
conteúdos relevantes (e até os não tão relevantes assim).</p>

<blockquote>É o que espera a equipe da PHP Review</blockquote>
