<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>PHP Review :: Reconhece este código?</title>
<meta name="keywords" content="hospedagem, revista, php, phpreview" />
<meta name="description" content="Hotsite da primeira edição da PHPReview" />
<link href="/css/coffee.css" rel="stylesheet" type="text/css" />
    
    <script src="/javascript/jquery-1.2.1.pack.js" type="text/javascript"></script>
    <script src="/javascript/jquery-easing.1.2.pack.js" type="text/javascript"></script>
    <script src="/javascript/jquery-easing-compatibility.1.2.pack.js" type="text/javascript"></script>
    <script src="/javascript/coda-slider.1.1.1.pack.js" type="text/javascript"></script>
    
    <!-- 
    The CSS. You can of course have this in an external .css file if you like.
    Please note that not all these styles may be necessary for your use of Coda-Slider, so feel free to take out what you don't need.
    -->
    
    <!-- Initialize each slider on the page. Each slider must have a unique id -->
    <script type="text/javascript">
    jQuery(window).bind("load", function() {
    jQuery("div#slider1").codaSlider()
    // jQuery("div#slider2").codaSlider()
    // etc, etc. Beware of cross-linking difficulties if using multiple sliders on one page.
    });
    </script>

</head>
<body>

<div id="templatemo_wrapper_outer">
<div id="templatemo_wrapper_inner">

	<div id="templatemo_header">
        <div id="site_title">
        	<a href="http://www.templatemo.com" target="_parent">
            	<img src="/images/templatemo_logo.png" alt="" />
            </a>
        </div>
    </div> <!-- end of templatemo_header -->
    
    <div id="templatemo_content">
    
    
    <!-- start of slider -->
    

<div class="slider-wrap">
	<div id="slider1" class="csw">
		<div class="panelContainer">
		
			<div class="panel" title="Bem Vindos">
				<div class="wrapper">
                
					<h1>Primeira edição está no ar!</h1>
                    
					<div class="image_wrapper fl_image">
	                    <img src="/images/qrcode.png" alt="QrCode"/>
                    </div>
                    
                    <p class="em_text">Parabéns por ter assinado a PHP Review, a equipe está muito grata pela sua escolha</p>

	            <p class="em_text">Enquanto você desfruta da sua revista, nós lhe oferecemos um cafezinho para acompanhar a degustação da primeira edição. Temos certeza que 
                    você irá gostar de ler tanto quanto gostamos de fazê-la.</p>
                    <p class="em_text">A equipe PHP Review agradece já a participação dos colaboradores desta edição, que acreditaram no projeto desde o início, e a todos os usuários 
                    já cadastrados no site. E aguardamos o retorno de todos com um feedback, dicas e sugestões. Estamos abertos a fazer desta uma revista cada vez mais 
                     interessante para todos vocês!</p>
                    <p class="em_text">Agora, navegue pelas páginas e saiba como colaborar com a revista.</p>
                    <p class="em_text">Muito Obrigado</p>
					<p><a href="#5" class="cross-link" title="Go to Page 5">&#171; Anterior</a> | <a href="#2" class="cross-link" title="Go to Page 2">Próximo &#187;</a></p>
				</div>
			</div>
			<div class="panel" title="Colabore">
				<div class="wrapper">
                
					<h1>Como colaborar com a revista</h1>
                    
                    <p>A PHP Review está sempre buscando suprir as necessidades dos programadores PHP, mas percisamos de você par anos ajudar nesta empreitada.</p>
                    <p>Veja abaixo as formas de ajudar a revista.</p>
                    <div class="cleaner_h20"></div>
                    <ul class="service_list">
                    	<li>Enviando artigos, matérias, tutoriais ou resumo dos eventos que você participar</li>
                        <li>Divulgando a revista em seu site ou seu blog</li>
                        <li>Anunciando na PHP Review, pois somente desta forma poderemos matê-la pública e gratuita, com a qualidade que você merece.</li>
                    </ul>
                    
                    <div class="cleaner_h20"></div>
					<p><a href="#1" class="cross-link" title="Go to Page 1">&#171; Anterior</a> | <a href="#3" class="cross-link" title="Go to Page 3">Próximo &#187;</a></p>
				</div>
			</div>		
            
            
			<div class="panel" title="Parceiros">
				<div class="wrapper">
					
            		<h1>Conheça os nossos parceiros</h1>
                    
                        <div class="portfolio_box margin_r50">
                        
                            <h3>Editora Novatec</h3>
                            <div class="port_img">
                                <a href="http://www.novatec.com.br/?idA=236" target="_parent"><img src="/images/novatec.png" alt="Novatec" /></a>
                            </div>
                            <p>A Novatec está nos ajudando na divulgação da revista e no fornecimento de livros para serem sorteados.</p>
                            <div class="button_01"><a href="http://www.novatec.com.br/?idA=236" target="_parent">Visite</a></div>
                            
                            <div class="cleaner"></div>
                        </div>
                        
                        <div class="portfolio_box margin_r50">
    
                            <h3>PHP SP</h3>
                            
                            <div class="port_img">
                                <a href="http://www.phpsp.org.br" target="_parent"><img src="/images/phpsp.png" alt="project 2" /></a>
                            </div>
                            <p>O GU PHPSP está ajudando ativamente na divulgação da revista.</p>
                            <div class="button_01"><a href="http://www.phpsp.org.br" target="_parent">Visite</a></div>
                            
                            <div class="cleaner"></div>                                               
                        </div>
                        
                    <div class="cleaner"></div>
                                        
                    <p><a href="#2" class="cross-link" title="Go to Page 2">&#171; Anterior</a> | <a href="#4" class="cross-link" title="Go to Page 4">Próximo &#187;</a></p>
                     
				</div>
			</div>
            
			<div class="panel" title="PHPinga">
				<div class="wrapper">
			 <h1>Espaço reservado para as suas confraternizações</h1>
      <div class="cleaner_h20"></div>
                   <p>Todo encontro de programadores que ser preze tem que ter o seu PHPinga, certo? </p>
                   <p>A partir da segunda edição da revista teremos um espaço para você divulgar os encontros do seu GU PHP ou as fotos da seu evento. </p>
                  <p>Envie as fotos para <a href="mailto:dicas@phpreview.net">dicas@phpreview.net</a>
                  juntamente com o nome do evento, a data em que ocorreu, o local e os integrantes das fotos. </p>
                          <div class="cleaner_h20"></div>
                    <div class="cleaner"></div>
					<p><a href="#3" class="cross-link" title="Go to Page 3">&#171; Anterior</a> | <a href="#5" class="cross-link" title="Go to Page 5">Próximo &#187;</a></p>
				</div>
			</div>
			<div class="panel" title="Anuncie">
				<div class="wrapper">
			                    <h1>Anuncie para um grupo seleto de Programdores PHP</h1>
                    
                   <p>A revista PHP Review é uma revista gratuita, porém, para manter a sua gratuidade dependemos de empresas para anunciarem o seu produto.</p>
		   <p>Se há em você o desejo de colaborar com este projeto, envie um e-mail para <a href='mailto:comercial@phpreview.net'>comercial@phpreview.net</a> que lhe enviaremos o
		      perfil dos assinantes da revista.</p>		
                    
                    <div class="cleaner_h20"></div>
                    
					<p><a href="#4" class="cross-link" title="Go to Page 4">&#171; Anterior</a> | <a href="#1" class="cross-link" title="Go to Page 1">Próximo &#187;</a></p>
				</div>
			</div>
			
		</div><!-- .panelContainer -->
	</div><!-- #slider1 -->
</div><!-- .slider-wrap -->

<p id="cross-links" style="width:0px; height: 0px; font-size:0; overflow: hidden;">
	Same-page cross-link controls:<br />
	<a href="#1" class="cross-link">Page 1</a> | <a href="#2" class="cross-link">Page 2</a> | <a href="#3" class="cross-link">Page 3</a> | <a href="#4" class="cross-link">Page 4</a> | <a href="#5" class="cross-link">Page 5</a>
</p>

    <!-- end of slider -->
      
	</div> 
	<!-- end of templatemo_content -->
    
    <div id="templatemo_footer"><span class="coffee_cup"></span>

	    Copyright © 2048 <a href="/">PHP Review</a> | 
        Designed by <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a> |
        Validate <a href="http://validator.w3.org/check?uri=referer">XHTML</a> &amp; 
        		 <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a>
      
	</div> <!-- end of templatemo_footer -->


</div> 
<!-- end of templatemo_wrapper_inner -->
</div> <!-- end of templatemo_wrapper_outer -->

</body>
</html>
