<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>:: PHP Review :: A sua nova revista on-line de PHP ::</title>
<meta name="keywords" content="revista, php, php review, programacao, vida de programador, design, tableless" />
<meta name="description" content="A PHP Review é a sua nova revista sobre PHP, mercado de trabalho e tudo o que envolve a programação." />
<link href="/css/global.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://www.phpreview.net/javascript/jquery.js"></script>
<script type="text/javascript" src="http://www.phpreview.net/javascript/jquery.masked.js"></script>
<script type="text/javascript" src="http://www.phpreview.net/javascript/phpreview.js"></script>
<script type="text/javascript" src="http://www.phpreview.net/javascript/cycle.js"></script>
<script type="text/javascript" src="http://widgets.twimg.com/j/2/widget.js"></script>
<script type="text/javascript">
    $().ready(function(){
        $('.project_image_box').cycle({
            fx: 'fade',
            timeout: 3000
        });
    });
</script>
</head>
<body>
<?php

?>
</body>
</html>
