<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>:: PHP Review :: A sua nova revista on-line de PHP ::</title>
<meta name="keywords" content="revista, php, php review, programacao, vida de programador, design, tableless" />
<meta name="description" content="A PHP Review é a sua nova revista sobre PHP, mercado de trabalho e tudo o que envolve a programação." />
<link href="/css/global.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/javascript/jquery.js"></script>
<script type="text/javascript" src="/javascript/jquery.masked.js"></script>
<script type="text/javascript" src="/javascript/phpreview.js"></script>
<script type="text/javascript" src="/javascript/cycle.js"></script>
<script type="text/javascript" src="http://widgets.twimg.com/j/2/widget.js"></script>
<script type="text/javascript">
    $().ready(function(){
        $('.project_image_box').cycle({
            fx: 'fade',
            timeout: 3000
        }
    )
    })
</script>
</head>
<body>
<div id="templatemo_header_wrapper">
	<div id="templatemo_header">

        <div id="site_title">
            <a href="/" title="PHP Review">
                <img src="/images/logo.png" alt="css templates" />
            </a>
      </div>

        <div id="templatemo_menu">

            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="<?= $this->url(array('controller'=>'index','action'=>'sobre.revista'),'default',true) ?>" >A Revista</a></li>
                <li><a href="<?= $this->url(array('controller'=>'edicoes','action'=>'index'),'default',true) ?>" >Edições</a></li>
                <li><a href="<?= $this->url(array('controller'=>'index','action'=>'nossa.equipe'),'default',true) ?>">A Equipe</a></li>
                <li><a href="<?= $this->url(array('controller'=>'usuario','action'=>'novo'),'default',true) ?>">Cadastre-se</a></li>
                <li><a href="<?= $this->url(array('controller'=>'contato','action'=>'index'),'default',true) ?>">Contato</a></li>
            </ul>

        </div> <!-- end of templatemo_menu -->

    </div>
</div>

<div id="templatemo_feature_wrapper">
	<div id="templatemo_feature">
		<div id="feature_left">
        	<h1>PHP Review no forno</h1>
            <p>Com previsão de inaguração para a primeira quinzena de agosto, a PHP Review promete inovar já na primeira edição.</p>
            <div class="button"><a href="#">aguarde!!!</a></div>
        </div>
        <div id="feature_right">

        	<div id="feature_image"><span></span>
            	<img src="/images/templatemo_image_01.png" alt="image" />
            </div>

        </div>

	</div> <!-- end of feature -->
</div> <!-- end of feature warpper -->

<div id="templatemo_content_wrapper">

    <div id="templatemo_content">

        <?php echo $this->layout()->content; ?>

    </div> <!-- end of content -->

    <div id="templatemo_sidebar">
        <div class="estatisticas">
           <p><b>Temos <?php echo $this->totalUsuarios ?> usuários cadastrados.</b></p>
           <a href="http://revistaphp.wordpress.com/" target="_blank"><img src="/images/wordpress.png" alt="Wordpress" /></a>
           <a href="http://twitter.com/phpreview" target="_blank"><img src="/images/twitter.png" alt="Twitter" /></a>
        </div>
        <div id="testimonial_newsletter" style="display:none">
            <div id="testimonial">
                <h2>Busca</h2>
                <?php // echo $this->Busca; ?>
                <form action="<?= $this->url(array('controller'=>'buscar','action'=>'index'),'default',true) ?>" method="post">
                	<input type="text" id="buscar_item" />
                    <input type="submit" name="submit" value="Buscar" id="busca_subscribe" />
                </form>
            </div>
            <div id="newsletter">
            	<h2>Newsletter</h2>
                <?php // echo $this->Newsletter; ?>
                <form action="<?= $this->url(array('controller'=>'index','action'=>'newsletter'),'default',true) ?>" method="post">
                	<input type="text" id="newsletter_email" />
                    <input type="submit" name="submit" value="Inscrever" id="newsletter_subscribe" />
                </form>
            </div>
    	</div>
        <?php
        if (is_array($this->noticias) && count($this->noticias) != 0){
        echo '<h2>Últimas <span>Notícias</span></h2>';
        foreach($this->noticias as $noticia){ ?>

        <div class="newsbox">
        	<div class="news_image"><span><?= $noticia->getDataPublicacao('d/m/y') ?></span><!-- <img src="/images/templatemo_image_04.png" alt="image" /> --></div>
            <p><?= $noticia->getTitulo() ?><br /> <em> (<?= $noticia->getUsuario()->getNome() ?>)</em> </p>
            <div class="cleaner"></div><div class="readmore"><a href="<?= $this->url(array('controller'=>'noticia','action'=>'read','id'=>$noticia->getId()),'default',true)?>">leia mais</a></div>
        </div>
        <?php } }?>
<script type="text/javascript">
new TWTR.Widget({
  version: 2, type: 'profile', rpp: 5,
  interval: 6000, width: 250, height: 250,
  theme: {
    shell: {
      background: '#80acbd', color: '#ffffff'
    },
    tweets: {
      background: '#ffffff', color: '#000000', links: '#228cb3'
    }
  },
  features: {
    scrollbar: false, loop: false, live: true, hashtags: true, timestamp: true,
    avatars: false, behavior: 'all'
  }
}).render().setUser('@phpreview').start();
</script>

    </div> <!-- end of slider -->

    <div class="cleaner_h30"></div>

    <div id="latest_projects">

	<div id="latest_project_text">
            <h2>Parceiros</h2>
            <p>	Aqui estão as empresas e sites que são parceiras da revista PHP Review e que apoiaram a revista desde sua concepção.</p>
        </div>

        <div class="project_image_box margin_r15">
            <a href="http://www.novatec.com.br/?idA=236" ><div class="project_image"><span></span>
            	<img src="/images/novatec.png" alt="Editora Novatec" />
            </div></a>
        </div>
	<div class="project_image_box margin_r15">
            <a href="http://www.digital3i.com" ><div class="project_image"><span></span>
            	<img src="images/digital3i.png" alt="Digital3i" />
            </div></a>
	  </div>

	<div class="project_image_box margin_r15">
            <a href="http://www.dnadigital.com.br" ><div class="project_image"><span></span>
                <img src="images/dnadigital.png" alt="Dna Digital" />
            </div></a>
	  </div>

      <div class="project_image_box">
          <a href="http://www.phpsp.org.br">
               <div class="project_image"><span></span>
            	<img src="/images/phpsp.png" alt="image 4" />
            </div></a>
          <a href="http://www.latinoware.org">
               <div class="project_image"><span></span>
            	<img src="/images/latinoware.png" alt="image 4" />
            </div></a>
	  </div>

    </div>
	<div  class="cleaner"></div>
</div> <!-- end of content wrapper -->

<div id="templatemo_footer_wrapper">
	<div id="templatemo_footer">
    	<div id="footer_title">Site Info.</div>

        <div class="footer_box">
        	<div class="cleaner_h40"></div>
        	Copyright © 2010 <a href="/">PHP Review</a><br />
        	Design por <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a><br />
                Valide <a href="http://validator.w3.org/check?uri=referer">XHTML</a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a>
        </div>

        <div class="footer_box" style="display:none">
        	<h2>Our Sponsor</h2>
            <div class="blog_image"><span></span><img src="images/templatemo_image_11.png" alt="web template" /></div>
            <p class="blog_section"><span>Monday, November 2010</span>
            Suscipit, nisi sapien dignissimnibh, ac vestibulum lorem urna in neque.</p>
      </div>

        <div class="footer_box">
       		<h2>Parceiros</h2>
            <ul>
            	<li><a href="http://www.novatec.com.br/?idA=236">Novatec Editora</a></li>
                <li><a href="http://www.php.net">PHP</a></li>
            </ul>
        </div>

        <div class="cleaner"></div>
    </div>
</div>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17973136-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>

</html>
