<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Corporate Website Template</title>
<meta name="keywords" content="corporate website, free css templates, CSS, HTML" />
<meta name="description" content="Corporate Template is a free CSS template provided by templatemo.com" />
<link href="/css/global.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="templatemo_header_wrapper">
	<div id="templatemo_header">

        <div id="site_title">
            <a href="http://www.templatemo.com" target="_parent">
                <img src="images/templatemo_logo.png" alt="css templates" />
                <span>FREE CSS TEMPLATES</span>
            </a>
      </div>


        <div id="templatemo_menu">

            <ul>
                <li><a href="#" class="current">Home</a></li>
                <li><a href="http://www.templatemo.com" target="_parent">Templates</a></li>
                <li><a href="http://www.flashmo.com" target="_parent">Flash Files</a></li>
                <li><a href="http://www.koflash.com" target="_parent">Gallery</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Contact</a></li>
            </ul>

        </div> <!-- end of templatemo_menu -->

    </div>
</div>

<div id="templatemo_feature_wrapper">
	<div id="templatemo_feature">

		<div id="feature_left">

        	<h1>Welcome to CSS Template</h1>
            <p>Duis vitae velit sed dui malesuada dignissim. Donec mollis aliquet ligula. Maecenas adipiscing elementum ipsum. Pellentesque vitae magna. Sed nec est. Suspendisse a nibh tristique justo rhoncus volutpat. Suspendisse vitae neque eget ante tristique vestibulum.</p>
            <div class="button"><a href="#">Read more</a></div>

        </div>

        <div id="feature_right">

        	<div id="feature_image"><span></span>
            	<img src="images/templatemo_image_01.png" alt="image" />
            </div>

        </div>

	</div> <!-- end of feature -->
</div> <!-- end of feature warpper -->

<div id="templatemo_content_wrapper">

    <div id="templatemo_content">

        <?php echo $this->layout()->content; ?>

    </div> <!-- end of content -->

    <div id="templatemo_sidebar">

        <h2>Latest <span>News</span></h2>
        <div class="newsbox">
        	<div class="news_image"><span></span><img src="/images/templatemo_image_04.png" alt="image" /></div>
            <p>Aenean cursus. Maecenas aliqu am, ligula id egestas suscipit, nisi sapien dignissim. </p>
            <div class="cleaner"></div><div class="readmore"><a href="#">read more</a></div>
        </div>
        <div class="newsbox">
        	<div class="news_image"><span></span><img src="/images/templatemo_image_05.png" alt="image" /></div>
            <p>estibulum ullamcorper eros vel lectus sagittis aliquet aliquam ante pretium. </p>
            <div class="cleaner"></div><div class="readmore"><a href="#">read more</a></div>
        </div>
        <div class="newsbox">
        	<div class="news_image"><span></span><img src="/images/templatemo_image_06.png" alt="image" /></div>
            <p>Praesent pretium purus ut lorem luctus ornare interdum diam eleifend. </p>
            <div class="cleaner"></div><div class="readmore"><a href="#">read more</a></div>
        </div>

        <div id="testimonial_newsletter">
            <div id="testimonial">
                <h2>Testimonial</h2>
                <p><img class="open" src="images/open.png" alt="opening tag" />urabitur adipiscing tellus eu arcu tincidunt condimentum. Aliquam ipsum felis, pulvinar at lacinia at, commodo ut nisi. Nullam egestas fermentum nis.<img class="close" src="images/close.png" alt="closing tag" /></p>
                <cite class="float_r"><a href="#">Vestibulum</a></cite>            </div>

            <div id="newsletter">
            	<h2>Newsletter</h2>
                <form action="#" method="get">

                	<input type="text" id="newsletter_email" />
                    <input type="submit" name="submit" value="Subscribe" id="newsletter_subscribe" />
                </form>
            </div>
    	</div>

    </div> <!-- end of slider -->

    <div class="cleaner_h30"></div>

    <div id="latest_projects">

	<div id="latest_project_text">
            <h2>Latest Projects</h2>
            <p>	Sedut perspiciatis unde omnis iste natus error sit volup tatem accus antium dolorem que lauda ntiumAt vero eos et accusamus et iusto odio.</p>
        </div>

        <div class="project_image_box margin_r15">
            <div class="project_image"><span></span>
            	<img src="images/templatemo_image_07.png" alt="image 1" />
            </div>
            <h5><a href="#">sed ut perspiciatis.</a></h5>
	  </div>

	<div class="project_image_box margin_r15">
            <div class="project_image"><span></span>
            	<img src="images/templatemo_image_08.png" alt="image 2" />
            </div>
        	<h5><a href="#">emque laudantium</a></h5>
	  </div>

	<div class="project_image_box margin_r15">
            <div class="project_image"><span></span>
            	<img src="images/templatemo_image_09.png" alt="image 3" />
            </div>
        <h5><a href="#">eaque ipsa quae</a></h5>
	  </div>

      <div class="project_image_box">
	<div class="project_image"><span></span>
            	<img src="images/templatemo_image_10.png" alt="image 4" />
            </div>
          <h5><a href="#">similique sunt.</a></h5>
	  </div>

    </div>

	<div  class="cleaner"></div>
</div> <!-- end of content wrapper -->

<div id="templatemo_footer_wrapper">
	<div id="templatemo_footer">
    	<div id="footer_title">Site Info.</div>

        <div class="footer_box">
        	<div class="cleaner_h40"></div>
        	Copyright © 2048 <a href="#">Your Company Name</a><br />
        	Designed by <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a><br />
            Validate <a href="http://validator.w3.org/check?uri=referer">XHTML</a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a>
        </div>

        <div class="footer_box">
        	<h2>Our Sponsor</h2>
            <div class="blog_image"><span></span><img src="images/templatemo_image_11.png" alt="web template" /></div>
            <p class="blog_section"><span>Monday, November 2010</span>
            Suscipit, nisi sapien dignissimnibh, ac vestibulum lorem urna in neque.</p>
      </div>

        <div class="footer_box">
       		<h2>Business partners</h2>
            <ul>
            	<li><a href="#">Cum sociis natoque penatibus</a></li>
                <li><a href="#">Vestibulum auctor odio eget</a></li>
                <li><a href="#">Praesent sollicitudin mollis</a></li>
                <li><a href="#">Quisque blandit eros et lorem</a></li>
            </ul>
        </div>

        <div class="cleaner"></div>
    </div>
</div>

</body>
</html>