<h2>Contato</h2>

<p>A revista PHP Review precisa muito da sua opinião para que se torne cada vez mais uma revista com a sua cara.
    Para qualquer sugestão, questionamento, dúvidas ou críticas entre em contato conosco através dos canais abaixo:</p>

<ul>
    <li><b>E-mail:</b> contato@phpreview.net</li>
    <li><b>Twitter:</b> <a href="http://twitter.com/phpreview">@phpreview</a></li>
    <li><b>Anuncie:</b> comercial@phpreview.net</li>
</ul>
<p>Temos interesse em sua participação, afinal, sem ela esse projeto nunca atingirá o resultado esperado. </p>
<blockquote>Equipe PHP Review</blockquote>
